version: "3"

includes:
  depl:
    taskfile: ./infra/taskfile.yaml
    dir: ./infra

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  run:
    desc: "Populate env from .env file and run service"
    deps: [install:godotenv]
    cmds:
      - godotenv -f ../.env task run-with-env
  run-with-env:
    required:
      vars:
        - MAILER_PORT
        - MAILER_LOG_LEVEL
        - MAILER_API_KEY
        - MAILER_FROM_ADDR
    cmds:
      - go run ./cmd/server
  format:
    desc: "Run gofumpt"
    deps: [install:gofumpt]
    cmds:
      - echo "Running formatter..."
      - gofumpt -l -w -e .
  lint:
    desc: "Run golangci-lint"
    deps: [install:lint]
    cmds:
      - echo "Running linters..."
      - golangci-lint run
    sources:
      - .golangci.yaml
      - ./**/*.go
      - go.mod
      - go.sum
  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - mkdir -p bin
      - go test -coverprofile bin/cover.out ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/cover.out

  test:cover:
    desc: "Run tests & show coverage"
    deps:
      - test
    cmds:
      - go tool cover -func bin/cover.out

  test:race:
    desc: "Run tests with a race flag"
    cmds:
      - go test -race -count=8 -failfast ./...

  test:integration:
    deps: [install:godotenv]
    desc: "Run integration tests"
    cmds:
      - godotenv -f .env.test task test:integration-with-env -- {{ .CLI_ARGS }}

  test:integration-with-env:
    vars:
      CONTAINER_NAME: "mailpit"
    requires:
      vars:
        - MAILER_TEST_SMTP_PASSWORD
        - MAILER_TEST_SMTP_FROM
        - MAILER_TEST_SMTP_HOST
        - MAILER_TEST_SMTP_PORT
        - MAILER_TEST_API_PORT
    cmds:
      - docker run -d --name {{ .CONTAINER_NAME }} -p {{ .MAILER_TEST_SMTP_PORT }}:1025 -p {{ .MAILER_TEST_API_PORT }}:8025 axllent/mailpit
      - defer: docker stop {{ .CONTAINER_NAME }} && docker rm {{ .CONTAINER_NAME }}
      - task: healthcheck:mailpit
        vars:
          CONTAINER_NAME: "{{ .CONTAINER_NAME }}"
      - go test -tags=integration ./... {{ .CLI_ARGS }}

  healthcheck:mailpit:
    requires:
      vars:
        - MAILER_TEST_API_PORT
    cmds:
      - |
        exit_code=0
        docker exec -t {{ .CONTAINER_NAME }} wget --server-response http://localhost:8025/readyz 2>&1 \
        | awk '/^  HTTP/{print $2}' \
        | grep 200 || exit_code=1
        while [ "$exit_code" -gt 0 ]; do
            sleep 3
            exit_code=0
            docker exec -t {{ .CONTAINER_NAME }} wget --server-response http://localhost:8025/readyz 2>&1 \
            | awk '/^  HTTP/{print $2}' \
            | grep 200 || exit_code=1
        done
        exit_code=0

  generate:
    desc: "Generate (used for mock generation)"
    deps: [install:mock]
    cmds:
      - echo "Running generators..."
      - go generate ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum

  install:
    desc: "Install all tools"
    deps:
      - install:lint
      - install:gofumpt
      - install:mock

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  install:gofumpt:
    desc: "Install gofumpt"
    cmds:
      - go install mvdan.cc/gofumpt@latest
    status:
      - command -v gofumpt

  install:mock:
    desc: "Install mockgen"
    cmds:
      - go install go.uber.org/mock/mockgen@latest
    status:
      - command -v mockgen
  install:godotenv:
    desc: "Install go dot env lib"
    cmds:
      - go install github.com/joho/godotenv/cmd/godotenv@latest
    status:
      - command godotenv
