swagger: "2.0"
info:
  title: v1/ratewatcher/rw.proto
  version: version not set
tags:
  - name: RateWatcherService
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/rate:
    get:
      summary: Get rate
      description: Get latest USD -> UAH exchange rate
      operationId: RateWatcherService_GetRate
      responses:
        "200":
          description: Returned successfully fetched exchange rate
          schema:
            $ref: '#/definitions/v1RateResponse'
          examples:
            application/json:
              data:
                rate: 42
              message: successfully got rate
              success: true
        "400":
          description: Returned when there was error on server side
          schema: {}
          examples:
            application/json:
              message: failed to get rate
              success: false
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - exchange rate
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1RateResponse:
    type: object
    properties:
      rate:
        type: number
        format: float
